apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-shopping-cart-base
  namespace: app-shopping-cart
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app-shopping-cart-base
    name: in-cluster
  project: default
  source:
    path: kustomize/apps/shopping-cart/base
    repoURL: ssh://git@github.com/f-a-a/checkbox_assessment.git
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-kustomize
