apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db-redis

resources:
  - namespace.yaml
  - secrets-provider.yaml

helmCharts:
  - repo: https://charts.bitnami.com/bitnami
    name: redis
    releaseName: db-redis
    namespace: db-redis
    valuesInline:
      global:
        storageClass: gp2
      master:
        persistence:
          enabled: true
      replica:
        persistence:
          enabled: true
      auth:
        enabled: true
        existingSecret: db-redis-secret
        existingSecretPasswordKey: db-redis-password

patches:
  - path: secrets-provider-volume-inject.yaml
    target:
      kind: StatefulSet
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /mnt/secrets-store
          name: secrets-store-inline
          readOnly: true
    target:
      kind: StatefulSet

