apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db-redis

resources:
  - namespace.yaml
  - secrets.yaml

helmCharts:
  - repo: https://charts.bitnami.com/bitnami
    name: redis
    releaseName: db-redis
    namespace: db-redis
    valuesInline:
      master:
        persistence:
          enabled: false
        podAntiAffinityPreset: hard
        nodeSelector:
          checkbox.ai/node-selection: dbs
      replica:
        persistence:
          enabled: false
        podAntiAffinityPreset: hard
        nodeSelector:
          checkbox.ai/node-selection: dbs
      auth:
        enabled: true
        existingSecret: db-redis-secret
        existingSecretPasswordKey: db-redis-password
