apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secrets-provider-volumeinject
spec:
  template:
    spec:
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: db-redis-secret-provider


